
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 24661
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        users = new javax.swing.JTextField();
        contras = new javax.swing.JPasswordField();
        jb_login = new javax.swing.JButton();
        jb_signup = new javax.swing.JButton();
        jd_tipo = new javax.swing.JDialog();
        jr_admin = new javax.swing.JRadioButton();
        jr_cacademico = new javax.swing.JRadioButton();
        jr_planta = new javax.swing.JRadioButton();
        jr_doc = new javax.swing.JRadioButton();
        jr_estudiante = new javax.swing.JRadioButton();
        aceptartipo = new javax.swing.JButton();
        jd_Ceo = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jt_nombreceo = new javax.swing.JTextField();
        numeroceo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        apellidoceo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nacionalidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        experiencia = new javax.swing.JTextField();
        labor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        acceptceo = new javax.swing.JButton();
        jd_admin = new javax.swing.JDialog();
        numeroadmin = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        apellidoadmin = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jt_nombreadmin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cargoadmin = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        adminarea = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        adminsubs = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        adminasistente = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        adminjefe = new javax.swing.JTextField();
        adminaccept = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jd_persaca = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        pa_apellido = new javax.swing.JTextField();
        pa_personas = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        pa_nombre = new javax.swing.JTextField();
        pa_lugar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        paccept = new javax.swing.JButton();
        pa_cargo = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        pa_puesto = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pa_registro = new javax.swing.JTextField();
        pa_becados = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        pa_nombre2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        pa_acuerdo = new javax.swing.JTextField();
        jd_persplanta = new javax.swing.JDialog();
        pp_registro = new javax.swing.JTextField();
        pp_carrera = new javax.swing.JTextField();
        pp_nombre = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pp_cargo = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        pp_facultad = new javax.swing.JTextField();
        pp_apellido = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        pp_clase = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        pp_accept = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jb_login.setText("Log In");

        jb_signup.setText("Sign Up");
        jb_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_signupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(49, 49, 49)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(users, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(contras)))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jb_login)
                        .addGap(110, 110, 110)
                        .addComponent(jb_signup)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_login)
                    .addComponent(jb_signup))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        buttonGroup1.add(jr_admin);
        jr_admin.setText("Administrativo");

        buttonGroup1.add(jr_cacademico);
        jr_cacademico.setText("Personal del Consejo Académico");

        buttonGroup1.add(jr_planta);
        jr_planta.setText("Personal de Planta");

        buttonGroup1.add(jr_doc);
        jr_doc.setText("Docente");

        buttonGroup1.add(jr_estudiante);
        jr_estudiante.setText("Estudiante");

        aceptartipo.setText("Aceptar");
        aceptartipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptartipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_tipoLayout = new javax.swing.GroupLayout(jd_tipo.getContentPane());
        jd_tipo.getContentPane().setLayout(jd_tipoLayout);
        jd_tipoLayout.setHorizontalGroup(
            jd_tipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tipoLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jd_tipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jr_planta)
                    .addComponent(jr_doc)
                    .addComponent(jr_estudiante)
                    .addComponent(aceptartipo)
                    .addComponent(jr_admin)
                    .addComponent(jr_cacademico))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jd_tipoLayout.setVerticalGroup(
            jd_tipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tipoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jr_admin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jr_cacademico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jr_planta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jr_doc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jr_estudiante)
                .addGap(18, 18, 18)
                .addComponent(aceptartipo)
                .addGap(43, 43, 43))
        );

        jLabel3.setText("Nombre");

        jt_nombreceo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nombreceoActionPerformed(evt);
            }
        });

        numeroceo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroceoActionPerformed(evt);
            }
        });

        jLabel11.setText("Numero de registro");

        jLabel12.setText("Apellido");

        jLabel13.setText("Nacionalidad");

        jLabel14.setText("Título universitario");

        titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloActionPerformed(evt);
            }
        });

        jLabel15.setText("Edad");

        jLabel16.setText("Años de Experiencia");

        jLabel17.setText("Años laborando");

        acceptceo.setText("Aceptar");
        acceptceo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptceoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_CeoLayout = new javax.swing.GroupLayout(jd_Ceo.getContentPane());
        jd_Ceo.getContentPane().setLayout(jd_CeoLayout);
        jd_CeoLayout.setHorizontalGroup(
            jd_CeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CeoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jd_CeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38)
                .addGroup(jd_CeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroceo)
                    .addComponent(apellidoceo)
                    .addComponent(nacionalidad)
                    .addComponent(titulo)
                    .addComponent(edad)
                    .addComponent(experiencia)
                    .addComponent(labor)
                    .addComponent(jt_nombreceo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CeoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acceptceo)
                .addGap(143, 143, 143))
        );

        jd_CeoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {apellidoceo, edad, experiencia, jt_nombreceo, labor, nacionalidad, numeroceo, titulo});

        jd_CeoLayout.setVerticalGroup(
            jd_CeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CeoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jd_CeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_nombreceo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_CeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(numeroceo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_CeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(apellidoceo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_CeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_CeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_CeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_CeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_CeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(labor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(acceptceo)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        numeroadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroadminActionPerformed(evt);
            }
        });

        jLabel18.setText("Numero de registro");

        jLabel19.setText("Apellido");

        jt_nombreadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nombreadminActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel20.setText("Cargo");

        jLabel21.setText("Area asignada");

        jLabel22.setText("Numero de subordinados");

        jLabel23.setText("Nombre de asistente");

        jLabel24.setText("Nombre de jefe");

        adminaccept.setText("Aceptar");
        adminaccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminacceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_adminLayout = new javax.swing.GroupLayout(jd_admin.getContentPane());
        jd_admin.getContentPane().setLayout(jd_adminLayout);
        jd_adminLayout.setHorizontalGroup(
            jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroadmin)
                    .addComponent(apellidoadmin)
                    .addComponent(jt_nombreadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoadmin)
                    .addComponent(adminarea)
                    .addComponent(adminsubs)
                    .addComponent(adminasistente)
                    .addComponent(adminjefe))
                .addGap(69, 69, 69))
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(adminaccept)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_adminLayout.setVerticalGroup(
            jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt_nombreadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(numeroadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(apellidoadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cargoadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(adminarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(adminsubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(adminasistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(adminjefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(adminaccept)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel25.setText("Numero de personas a su cargo");

        jLabel26.setText("Apellido");

        jLabel27.setText("Lugar de segundo trabajo");

        pa_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pa_nombreActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre");

        paccept.setText("Aceptar");
        paccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacceptActionPerformed(evt);
            }
        });

        jLabel28.setText("Cargo");

        jLabel29.setText("Puesto");

        jLabel30.setText("Cantidad de becados");

        pa_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pa_registroActionPerformed(evt);
            }
        });

        jLabel31.setText("Numero de registro");

        jLabel32.setText("Nombre de segundo trabajo");

        jLabel33.setText("Nombre de acuerdo con universidad");

        javax.swing.GroupLayout jd_persacaLayout = new javax.swing.GroupLayout(jd_persaca.getContentPane());
        jd_persaca.getContentPane().setLayout(jd_persacaLayout);
        jd_persacaLayout.setHorizontalGroup(
            jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_persacaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38)
                .addGroup(jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pa_registro)
                    .addComponent(pa_apellido)
                    .addComponent(pa_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pa_cargo)
                    .addComponent(pa_puesto)
                    .addComponent(pa_becados)
                    .addComponent(pa_personas)
                    .addComponent(pa_lugar)
                    .addComponent(pa_nombre2)
                    .addComponent(pa_acuerdo))
                .addGap(69, 69, 69))
            .addGroup(jd_persacaLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(paccept)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_persacaLayout.setVerticalGroup(
            jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_persacaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pa_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(pa_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(pa_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(pa_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(pa_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(pa_becados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(pa_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(pa_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(pa_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_persacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(pa_acuerdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(paccept)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pp_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp_registroActionPerformed(evt);
            }
        });

        pp_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp_nombreActionPerformed(evt);
            }
        });

        jLabel34.setText("Numero de registro");

        jLabel6.setText("Nombre");

        jLabel35.setText("Cargo");

        jLabel36.setText("Clase");

        jLabel37.setText("Facultad");

        jLabel38.setText("Carrera");

        jLabel39.setText("Apellido");

        pp_accept.setText("Aceptar");
        pp_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp_acceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_persplantaLayout = new javax.swing.GroupLayout(jd_persplanta.getContentPane());
        jd_persplanta.getContentPane().setLayout(jd_persplantaLayout);
        jd_persplantaLayout.setHorizontalGroup(
            jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_persplantaLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(pp_accept)
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_persplantaLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGap(38, 38, 38)
                    .addGroup(jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pp_registro)
                        .addComponent(pp_apellido)
                        .addComponent(pp_cargo)
                        .addComponent(pp_facultad)
                        .addComponent(pp_carrera)
                        .addComponent(pp_clase)
                        .addComponent(pp_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                    .addGap(23, 23, 23)))
        );
        jd_persplantaLayout.setVerticalGroup(
            jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_persplantaLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(pp_accept)
                .addGap(51, 51, 51))
            .addGroup(jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_persplantaLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(pp_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(pp_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel39)
                        .addComponent(pp_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(pp_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(pp_facultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel38)
                        .addComponent(pp_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(jd_persplantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(pp_clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(110, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cuenta");

        jMenuItem1.setText("Log In/Sign Up");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sign out");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Modificar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logIn() {
        jd_login.setModal(true);
        jd_login.pack();
        jd_login.setLocationRelativeTo(this);
        jd_login.setVisible(true);
    }

    private void tipo() {
        jd_tipo.setModal(true);
        jd_tipo.pack();
        jd_tipo.setLocationRelativeTo(this);
        jd_tipo.setVisible(true);
    }

    private void ceo() {
        jd_Ceo.setModal(true);
        jd_Ceo.pack();
        jd_Ceo.setLocationRelativeTo(this);
        jd_Ceo.setVisible(true);
    }
    private void admin() {
        jd_admin.setModal(true);
        jd_admin.pack();
        jd_admin.setLocationRelativeTo(this);
        jd_admin.setVisible(true);
    }
    private void pa() {
        jd_persaca.setModal(true);
        jd_persaca.pack();
        jd_persaca.setLocationRelativeTo(this);
        jd_persaca.setVisible(true);
    }
    private void pp() {
        jd_persplanta.setModal(true);
        jd_persplanta.pack();
        jd_persplanta.setLocationRelativeTo(this);
        jd_persplanta.setVisible(true);
    }

    private void jb_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_signupActionPerformed
        if (usuarios.size() == 0) {
            usuarios.add(users.getText());
            contraseñas.add(contras.getText());
            users.setText("");
            contras.setText("");
            jd_login.setVisible(false);
            ceo();
        } else {
            usuarios.add(users.getText());
            contraseñas.add(contras.getText());
            users.setText("");
            contras.setText("");
            jd_login.setVisible(false);
            tipo();
        }
    }//GEN-LAST:event_jb_signupActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        logIn();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void jt_nombreceoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nombreceoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nombreceoActionPerformed

    private void tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloActionPerformed

    private void numeroceoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroceoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroceoActionPerformed
    //Di doble click por error y aparecieron estos
    
    private void acceptceoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptceoActionPerformed
        u.add(new Ceo());
        ((Ceo)u.get(0)).setNombre(this.jt_nombreceo.getText());
        ((Ceo)u.get(0)).setApellido(this.apellidoceo.getText());
        ((Ceo)u.get(0)).setAñosexp(Integer.parseInt(this.experiencia.getText()));
        ((Ceo)u.get(0)).setAñoslabor(Integer.parseInt(this.labor.getText()));
        ((Ceo)u.get(0)).setNacionalidad(this.nacionalidad.getText());
        ((Ceo)u.get(0)).setRegistro(Integer.parseInt(this.numeroceo.getText()));
        ((Ceo)u.get(0)).setTitulo(this.titulo.getText());
        ((Ceo)u.get(0)).setEdad(Integer.parseInt(this.edad.getText()));
        jt_nombreceo.setText("");
        apellidoceo.setText("");
        experiencia.setText("");
        labor.setText("");
        nacionalidad.setText("");
        numeroceo.setText("");
        titulo.setText("");
        edad.setText("");
        this.jd_Ceo.setVisible(false);
    }//GEN-LAST:event_acceptceoActionPerformed

    private void aceptartipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptartipoActionPerformed
        if(this.jr_admin.isSelected()){
            admin();
        }else if(this.jr_cacademico.isSelected()){
            pa();
        }else if(this.jr_doc.isSelected()){
            pp();
        }else if(this.jr_estudiante.isSelected()){
            
        }else if(this.jr_planta.isSelected()){
            
        }
    }//GEN-LAST:event_aceptartipoActionPerformed

    private void numeroadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroadminActionPerformed

    private void jt_nombreadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nombreadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nombreadminActionPerformed

    private void adminacceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminacceptActionPerformed
        u.add(new Administrativo(this.jt_nombreadmin.getText(),Integer.parseInt(this.numeroadmin.getText()),this.apellidoadmin.getText(), this.cargoadmin.getText(), this.adminarea.getText(), Integer.parseInt(this.adminsubs.getText()),this.adminasistente.getText(),this.adminjefe.getText()) ) ;
        jd_admin.setVisible(false);
    }//GEN-LAST:event_adminacceptActionPerformed

    private void pa_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pa_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pa_nombreActionPerformed

    private void pacceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacceptActionPerformed
        u.add(new PersonalAcademico(pa_nombre.getText(),Integer.parseInt(pa_registro.getText()),pa_apellido.getText(),pa_cargo.getText(),pa_puesto.getText(),Integer.parseInt(pa_becados.getText()),Integer.parseInt(pa_personas.getText()),pa_lugar.getText(),pa_nombre2.getText(),pa_acuerdo.getText()));
        jd_persaca.setVisible(false);
    }//GEN-LAST:event_pacceptActionPerformed

    private void pa_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pa_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pa_registroActionPerformed

    private void pp_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pp_registroActionPerformed

    private void pp_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pp_nombreActionPerformed

    private void pp_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp_acceptActionPerformed
        u.add(new PersonalPlanta(pp_nombre.getText(),Integer.parseInt(pp_registro.getText()),pp_apellido.getText(),pp_cargo.getText(),pp_facultad.getText(),pp_carrera.getText(),pp_clase.getText()));
        jd_persplanta.setVisible(false);
    }//GEN-LAST:event_pp_acceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptceo;
    private javax.swing.JButton aceptartipo;
    private javax.swing.JButton adminaccept;
    private javax.swing.JTextField adminarea;
    private javax.swing.JTextField adminasistente;
    private javax.swing.JTextField adminjefe;
    private javax.swing.JTextField adminsubs;
    private javax.swing.JTextField apellidoadmin;
    private javax.swing.JTextField apellidoceo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cargoadmin;
    private javax.swing.JPasswordField contras;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField experiencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_signup;
    private javax.swing.JDialog jd_Ceo;
    private javax.swing.JDialog jd_admin;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_persaca;
    private javax.swing.JDialog jd_persplanta;
    private javax.swing.JDialog jd_tipo;
    private javax.swing.JRadioButton jr_admin;
    private javax.swing.JRadioButton jr_cacademico;
    private javax.swing.JRadioButton jr_doc;
    private javax.swing.JRadioButton jr_estudiante;
    private javax.swing.JRadioButton jr_planta;
    private javax.swing.JTextField jt_nombreadmin;
    private javax.swing.JTextField jt_nombreceo;
    private javax.swing.JTextField labor;
    private javax.swing.JTextField nacionalidad;
    private javax.swing.JTextField numeroadmin;
    private javax.swing.JTextField numeroceo;
    private javax.swing.JTextField pa_acuerdo;
    private javax.swing.JTextField pa_apellido;
    private javax.swing.JTextField pa_becados;
    private javax.swing.JTextField pa_cargo;
    private javax.swing.JTextField pa_lugar;
    private javax.swing.JTextField pa_nombre;
    private javax.swing.JTextField pa_nombre2;
    private javax.swing.JTextField pa_personas;
    private javax.swing.JTextField pa_puesto;
    private javax.swing.JTextField pa_registro;
    private javax.swing.JButton paccept;
    private javax.swing.JButton pp_accept;
    private javax.swing.JTextField pp_apellido;
    private javax.swing.JTextField pp_cargo;
    private javax.swing.JTextField pp_carrera;
    private javax.swing.JTextField pp_clase;
    private javax.swing.JTextField pp_facultad;
    private javax.swing.JTextField pp_nombre;
    private javax.swing.JTextField pp_registro;
    private javax.swing.JTextField titulo;
    private javax.swing.JTextField users;
    // End of variables declaration//GEN-END:variables
    ArrayList<Universidad> u = new ArrayList();
    ArrayList usuarios = new ArrayList();
    ArrayList contraseñas = new ArrayList();
}
//No pude man, en clase presté atención, iba viendo si le entendía y todo el rollo pero a la hora de la hora no pude. F. Voy a retirar el lab y en este tiempo voy a estudiar para entenderle mejor y así que me pueda ir bien en el siguiente trimestre.